[tool.poetry]
name = "hackathon-2023"
version = "0.1.0"
description = ""
authors = ["Bryce York <bryce@bryceyork.com>"]
readme = "README.md"
packages = [{include = "hackathon_2023"}]

[tool.poetry.dependencies]
python = "^3.9"
slack-sdk = "^3.21.3"
slack-bolt = "^1.18.0"
fastapi = "^0.103.0"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
python-multipart = "^0.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

